config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users
  resources :posts do
    resources :comments, only: :create
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  
  post 'follow/:id', to: 'relationships#follow', as: 'follow'
  post 'unfollow/:id', to: 'relationships#unfollow', as: 'unfollow'
  get 'users/following/:user_id', to: 'users#following', as: 'users_following'
  get 'users/follower/:user_id', to: 'users#follower', as: 'users_follower'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  validates :text, presence: true, unless: :was_attached?
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  def was_attached?
    self.image.attached?
  end

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true, uniqueness: { scope: :followed_id }
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :icon
  has_many :likes, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  validates :name, :account, presence: true
  validates :password, presence: true, on: :create
  validates :account, uniqueness: true

  VALID_ACCOUNT_REGEX = /\A[\w\d.@_-]+\z/i
  validates :account, format: { with: VALID_ACCOUNT_REGEX }
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: "には英字と数字の両方を含めて設定してください",  on: :create

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :account])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :icon, :email])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comments = @post.comments.includes(:user)
    if @comment.save
      redirect_to post_path(@post)
    else
      @error_comment = @comment
      render "posts/show"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :post_params

  def create
    like = current_user.likes.new(post_id: @post.id)
    like.save
  end

  def destroy
    like = current_user.likes.find_by(post_id: @post.id)
    like.destroy
  end

  private

  def post_params
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :show, :update]

  def index
    posts = Post.includes(:user)
    user = User.find(current_user.id)
    followings = user.following_user
    @recommendation_users = User.where.not(id: current_user.id).where.not(id: followings).order("RAND()").limit(5)
    @timeline = posts.where(user_id: followings, created_at: 24.hours.ago..).or(posts.where(user_id: user, created_at: 24.hours.ago..)).order("created_at DESC")
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def edit
    unless @post.user_id == current_user.id
      redirect_to action: :index
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def show
    if @post.user_id != current_user.id && @post.created_at < 24.hours.ago
      redirect_to root_path
    end
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @like = Like.new
  end

  def search
    user = current_user
    followings = user.following_user
    @recommendation_users = User.where.not(id: current_user.id).where.not(id: followings).order("RAND()").limit(5)
    @posts = SearchService.search(params[:keyword])
  end

  private

  def post_params
    params.require(:post).permit(:text, :image).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def follow
    current_user.follow(params[:id])
    render :create
  end

  def unfollow
    current_user.unfollow(params[:id])
    render :destroy
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    user = current_user
    followings = user.following_user
    @users = User.where.not(id: current_user.id).where.not(id: followings).order("RAND()")
  end

  def show
    @user = User.find(params[:id])
    @user_posts = @user.posts.order("created_at DESC")
    @posts = @user.posts.where(created_at: 24.hours.ago..).order("created_at DESC")
    @followings = @user.following_user
    @followers = @user.follower_user
    own_followings =current_user.following_user
    @recommendation_users = User.where.not(id: current_user.id).where.not(id: own_followings).order("RAND()").limit(5)
  end

  def edit
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to root_path
    end
    @icon = user.icon
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def following
    @user = User.find(params[:user_id])
    @followings = @user.following_user
    @followers = @user.follower_user
    own_followings =current_user.following_user
    @recommendation_users = User.where.not(id: current_user.id).where.not(id: own_followings).order("RAND()").limit(5)
  end

  def follower
    @user = User.find(params[:user_id])
    @followers = @user.follower_user
    @followings = @user.following_user
    own_followings =current_user.following_user
    @recommendation_users = User.where.not(id: current_user.id).where.not(id: own_followings).order("RAND()").limit(5)
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dayglass</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%# <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css"> %>
    <link rel="stylesheet" href="reset.css">
    <%= favicon_link_tag "favicon.ico" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <% if user_signed_in? %>
        <header class="header">
          <div class="header-contents">
            <div class="left-header">
              <%= link_to root_path do %>
                <%= image_tag "logo.png", class: "logo" %>
              <% end %>
              <%= form_with url: search_posts_path, local: true, method: :get, class: "search-form" do |f| %>
                <%= f.text_field :keyword, placeholder: "検索", class: "search-input" %>
                <% f.submit %>
              <% end %>
            </div>
            <div class="right-header">
              <div class="user-nav">
                <%= link_to current_user.account, user_path(current_user.id) %>
                <%= link_to edit_user_path(current_user), class: "setting" do %>
                  <i class="fa-solid fa-gear"></i>
                <% end %>
              </div>
              <div class="new-post-icon">
                <%= link_to new_post_path, class: "new-post" do %>
                <i class="fa-regular fa-pen-to-square"></i>
                <% end %>
              </div>
            </div>
          </div>
        </header>
      <% end %>
      <%= yield %>
    </div>
    <%# SP用 %>
    <% if user_signed_in? %>
      <footer>
        <div class="left-footer">
          <%= form_with url: search_posts_path, local: true, method: :get, class: "search-form" do |f| %>
            <%= f.text_field :keyword, placeholder: "検索", class: "search-input" %>
            <% f.submit %>
          <% end %>
        </div>
        <div class="sp-sub-contents">
          <%= link_to users_path do %>
            <i class="fa-solid fa-user-group"></i>
          <% end %>
        </div>
        <div class="new-post-icon">
          <%= link_to new_post_path, class: "new-post" do %>
          <i class="fa-regular fa-pen-to-square"></i>
          <% end %>
        </div>
      </footer>
    <% end %>
    <%# /SP用 %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if post.liked_by?(current_user) %>
  <%= link_to post_likes_path(post), method: :delete, remote: true do %>
    <i class="fa-solid fa-heart margin-r10"></i>
  <% end %>
<% else %>
  <%= link_to post_likes_path(post), method: :post, remote: true do %>
    <i class="fa-regular fa-heart margin-r10"></i>
  <% end %>
<% end %>
<% unless post.likes.count == 0 %>
  <div class="likes-count">
    <%= post.likes.count %>
    <ul class="likes-lists b">
      <% post.liked_users.each do |user| %>
        <li><%= link_to user.name, user_path(user) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/likes/create.js.erb
document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j(render partial: 'likes/like', locals: { post: @post }) %>'

app/views/likes/destroy.js.erb
document.getElementById('post_<%= @post.id %>').innerHTML = '<%= j(render partial: 'likes/like', locals: { post: @post }) %>'

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f| %>
  <%= render "layouts/error_messages", model: f.object %>
  <%= f.text_area :text, placeholder: "投稿する…", rows: "10", class: "text-field" %>
  <div class="image-area">
    <label class="form-image">
      <div class="image-file b">画像</div>
      <%= f.file_field :image, class: "hidden", id: "post_image" %>
    </label>
    <div id="image-list"></div>
  </div>
  <%= f.submit "投稿", class: "send-btn" %>
<% end %>

app/views/posts/_post.html.erb
<div class="content">
  <div class="upper-content">
    <div class="user-area">
      <div class="user-icon">
        <%= link_to user_path(post.user.id) do %>
          <% if post.user.icon.attached? %>
            <%= image_tag post.user.icon, class: "icon" %>
          <% else %>
            <%= image_tag "default_user.png", class: "icon" %>
          <% end %>
      </div>
      <div class="user">
          <div class="user-name b">
            <%= post.user.name %>
          </div>
        <% end %>
        <div class="limit-time">
          <% if post.created_at < (Time.now - 24.hours) %>
            <div class="time-ago-in-words-black">
              <%= time_ago_in_words(post.created_at) %>
            </div>
          <% elsif post.created_at < (Time.now - 21.hours) %>
            <div class="time-ago-in-words-red">
              <%= time_ago_in_words(post.created_at) %>
            </div>
          <% else %>
            <div class="time-ago-in-words">
              <%= time_ago_in_words(post.created_at) %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="leader">
      <i class="fa-solid fa-ellipsis"></i>
      <ul class="leader_list">
        <li>
          <%= link_to "詳細", post_path(post.id), method: :get %>
        </li>
        <% if current_user.id == post.user_id %>
          <li>
            <%= link_to '編集', edit_post_path(post.id), method: :get %>
          </li>
          <li>
            <%= link_to "削除", post_path(post.id), method: :delete, data: { confirm: "削除しますか？" } %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="content-post">
    <p class="nl-text"><%= post.text %></p>
    <div class="post-image-field">
      <%= link_to image_tag(post.image.variant(resize: "640x720")), post_path(post.id), class: "post-image" if post.image.attached? %>
    </div>
  </div>

  <div class="reaction">
    <div class="heart margin-r26">
      <div class="like" id="post_<%= post.id %>">
        <%= render partial: "likes/like", locals: { post: post, like: @like } %>
      </div>
    </div>

    <div class="comment2 margin-r26">
      <%= link_to post_path(post.id) do %>
        <i class="fa-regular fa-comment margin-r5"></i>
        <% unless post.comments.count == 0 %>
          <%= post.comments.count %>
        <% end %>
      <% end %>
    </div>
    
    <%#<div class="dayglass margin-r26">
      <i class="fa-regular fa-hourglass margin-r5"></i>
    </div>%>
  </div>
</div>

app/views/posts/_recommendation.html.erb
<div class="recommendation">
  <div class="upper-recommendation">
    <p class="recommend">おすすめ</p>
    <div class="more">
      <%= link_to "もっと見る", users_path %>
    </div>
  </div>
  <div class="recommendation-users">
    <% recommendation_users.each do |recommendation_user| %>
      <div class="recommendation-upper-content">
        <div class="user-area">
          <div class="user-icon">
            <%= link_to user_path(recommendation_user) do %>
              <% if recommendation_user.icon.attached? %>
                <%= image_tag recommendation_user.icon, class: "icon" %>
              <% else %>
                <%= image_tag "default_user.png", class: "icon" %>
              <% end %>
          </div>
          <div class="user">
              <div class="recommendation-user-name b">
                <%= recommendation_user.name %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="mini-footer">
  ©2022 STUDIO PAGURO
</div>

app/views/posts/edit.html.erb
<div class="main-contents">
  <div class="edit-page">
    <div class="post-form">
      <h4 class="title">編集する</h4>
      <%= render partial: "form", locals: { post: @post } %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main-contents">
  <div class="time-line">
    <div class="contents">
      <% if @timeline.blank? %>
        <h4 class="title">フォロー中または自分の24時間以内の投稿はありません。</h4>
      <% else %>
        <% @timeline.each do |post| %>
          <%= render partial: "post", locals: { post: post } %>
        <% end %>
      <% end %>
    </div>
    <div class="sub-contents">
      <%= render partial: "recommendation", locals: { recommendation_users: @recommendation_users } %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main-contents">
  <div class="post-form">
    <h4 class="title">投稿する</h4>
    <%= render partial: "form", locals: { post: @post } %>
  </div>
</div>

app/views/posts/search.html.erb
<div class="main-contents">
  <div class="time-line">
    <div class="contents">
      <% if @posts.blank? %>
        <h4 class="title">フォロー中または自分の24時間以内の投稿はありません。</h4>
      <% else %>
        <% @posts.each do |post| %>
          <%= render partial: "post", locals: { post: post } %>
        <% end %>
      <% end %>
    </div>
    <div class="sub-contents">
      <%= render partial: "recommendation", locals: { recommendation_users: @recommendation_users } %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main-contents">
  <div class="time-line">
    <div class="detailed-content">
      <div class="upper-content">
        <div class="user-area">
          <div class="user-icon2">
            <%= link_to user_path(@post.user.id) do %>
              <% if @post.user.icon.attached? %>
                <%= image_tag @post.user.icon, class: "icon" %>
              <% else %>
                <%= image_tag "default_user.png", class: "icon" %>
              <% end %>
          </div>
          <div class="user">
              <div class="user-name b">
                <%= @post.user.name %>
              </div>
            <% end %>
            <div class="limit-time">
              <% if @post.created_at < (Time.now - 21.hours) %>
                <div class="time-ago-in-words-red">
                  <%= time_ago_in_words(@post.created_at) %>
                </div>
              <% else %>
                <div class="time-ago-in-words">
                  <%= time_ago_in_words(@post.created_at) %>
                </div>
              <% end %>
            </div>
          </div>
        </div>

        <% if current_user.id == @post.user_id %>
          <div class="leader">
            <i class="fa-solid fa-ellipsis"></i>
            <ul class="leader_list">
              <li>
                <%= link_to '編集', edit_post_path(@post.id), method: :get %>
              </li>
              <li>
                <%= link_to '削除', post_path(@post.id), method: :delete, data: { confirm: "削除しますか？" } %>
              </li>
            </ul>
          </div>
        <% end %>
      </div>

      <div class="detailed-content_post">
        <p class="nl-text"><%= @post.text %></p>
        <div class="post-image-field">
          <%= image_tag @post.image.variant(resize: "974x720"), class: "post-image" if @post.image.attached? %>
        </div>
      </div>

      <div class="reaction-area">
        <div class="heart reaction-icon">
          <div class="like" id="post_<%= @post.id %>">
            <%= render partial: "likes/like", locals: { post: @post, like: @like } %>
          </div>
        </div>

        <div class="comment2 reaction-icon">
          <i class="fa-regular fa-comment margin-r5"></i>
          <% unless @post.comments.count == 0 %>
            <%= @post.comments.count %>
          <% end %>
        </div>

        <%#<div class="dayglass reaction-icon">
          <i class="fa-regular fa-hourglass margin-r10"></i>
        </div>%>

        <div class="comment-form-area">
          <%= form_with(model: [@post, @comment], class: "form", local: true) do |f| %>
            <% if @error_comment.present? %>
              <%= f.text_area :text, placeholder: @error_comment.errors.full_messages.first, rows: "1", class: "comment-form-error" %>
            <% else %>
              <%= f.text_area :text, placeholder: "コメントする", rows: "1", class: "comment-form" %>
            <% end %>
            <%= f.submit "投稿する", class: "btn" %>
          <% end %>
        </div>
      </div>
     
      <div class="comments">
        <% @comments.each do |comment| %>
          <div class="comment-area">
            <div class="user-icon">
              <% if comment.user.icon.attached? %>
                <%= image_tag comment.user.icon, class: "icon" %>
              <% else %>
                <%= image_tag "default_user.png", class: "icon" %>
              <% end %>
            </div>
            <div class="comment">
              <p><span class="b"><%= link_to comment.user.name, user_path(comment.user_id) %></span>  - - - <%= time_ago_in_words(comment.created_at) %></p>
              <p class="nl-text"><%= comment.text %></p>
            </div>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/relationships/_follow.html.erb
<% unless user == current_user %>
  <% if current_user.following?(user) %>
    <%= link_to "フォロー中", unfollow_path(user), method: :post, remote: true, class: "following-btn" %>
  <% else %>
    <%= link_to "フォロー", follow_path(user), method: :post, remote: true, class: "follow-btn" %>
  <% end %>
<% end %>

app/views/relationships/create.js.erb
document.getElementById('follow_form').innerHTML = '<%= j(render partial: 'relationships/follow', locals: { user: @user }) %>'

app/views/relationships/destroy.js.erb
document.getElementById('follow_form').innerHTML = '<%= j(render partial: 'relationships/follow', locals: { user: @user }) %>'

app/views/users/_info.html.erb
<div class="user-upper-content">
  <div class="user-area2">
    <div class="user-icon2">
      <% if user.icon.attached? %>
        <%= image_tag user.icon, class: "icon2" %>
      <% else %>
        <%= image_tag "default_user.png", class: "icon2" %>
      <% end %>
    </div>
    <div class="user2">
      <div class="user-name2 b">
        <%= link_to user.name, user_path(user.id) %>
      </div>
      <div class="user-account">
        <%= user.account %>
      </div>
      <div class="follow-counts b">
        <div class="follow-count ">
          <% if followings.count == 0 %>
            <%= "#{followings.count} フォロー中" %>
          <% else %>
            <%= link_to "#{followings.count} フォロー中", users_following_path(user) %>
          <% end %>
        </div> 
        <div class="follower-count">
          <% if followers.count == 0 %>
            <%= "#{followers.count} フォロワー" %>
          <% else %>
            <%= link_to "#{followers.count} フォロワー", users_follower_path(user) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% if current_user != user %>
    <div id="follow_form">
      <%= render partial: "relationships/follow", locals: { user: user } %>
    </div>
  <% else %>
    <div class="logout-btn">
      <%= link_to "ログアウト", destroy_user_session_path, class: "logout", method: :delete %>
    </div>
  <% end %>
</div>
<div class="user-profile text">
  <%= @user.profile %>
</div>

app/views/users/edit.html.erb
<div class="main-contents">
  <div class="time-line centering">
    <div class="profile-edit">
      <%= form_with model: current_user, local: true do |f|%>
        <% if current_user.errors.any? %>
        <% end %>
        <div class="profile-image-edit">
          <div class="edit-user-icon">
            <% if @icon.present? %>
              <%= image_tag @icon, class: "edit-icon" %>
            <% else %>
              <%= image_tag "default_user.png", class: "edit-icon" %>
            <% end %>
          </div>
          <div class="upper-profile-area">
            <div class="profile-account-area">
              <div class="profile-account b">
                <%= current_user.account %>
              </div>
              <label class="form-icon">
                <div class="icon-file">プロフィール写真を変更</div> 
                <%= f.file_field :icon, class: "hidden" %>
              </label>
            </div>
            <div class="destroy">
              <%= link_to "アカウント削除", user_path(current_user), method: :delete, class: "account-destroy", data: { confirm: "アカウントを削除すると、アカウントの全ての情報が削除され、元に戻す事はできません。アカウントを削除しますか？"} %>
            </div>
          </div>
        </div>
        <div class="user-form">
          <%#= render "layouts/error_messages", model: f.object %>

          <div class="field">
            <%= f.label :name, "名前" %><br />
            <% if current_user.errors.include?(:name) %>
              <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "profile-box-error", placeholder: current_user.errors.full_messages_for(:name).first %>
            <% else %>
            <%= f.text_field :name, autofocus: true, class: "profile-box" %>
            <% end %>
          </div>

          <div class="field">
            <%= f.label :email, "Ｅメール" %><br />
            <% if current_user.errors.include?(:email) %>
              <%= f.email_field :email, autocomplete: "email", class: "profile-box-error", placeholder: current_user.errors.full_messages_for(:email).first %>
            <% else %>
              <%= f.email_field :email, class: "profile-box" %>
            <% end %>
          </div>

          <div class="field">
            <%= f.label :profile, "自己紹介" %><br />
            <%= f.text_area :profile, class: "profile-box2" %>
          </div>
          
          <div class="actions">
            <%= f.submit "保存する", class: "btn save-btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/follower.html.erb
<div class="main-contents">
  <div class="time-line">
    <div class="contents">
      <div class="user-info">
        <%= render partial: "info", locals: { user: @user, followings: @followings, followers: @followers } %>
      </div>
      <div class="content">
        <h4 class="title">フォロワー</h4>
        <% @followers.each do |follower| %>
          <div class="follow-content">
            <div class="follow-upper-content">
              <div class="user-area">
                <div class="user-icon">
                  <%= link_to user_path(follower) do %>
                    <% if follower.icon.attached? %>
                      <%= image_tag follower.icon, class: "icon" %>
                    <% else %>
                      <%= image_tag "default_user.png", class: "icon" %>
                    <% end %>
                </div>
                <div class="user">
                    <div class="user-name b">
                      <%= follower.name %>
                    </div>
                    <div class="follow-account">
                      <%= follower.account %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="follow-user-profile text">
              <%= follower.profile %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="sub-contents">
      <%= render partial: "posts/recommendation", locals: { recommendation_users: @recommendation_users } %>
    </div>
  </div>
</div>

app/views/users/following.html.erb
<div class="main-contents">
  <div class="time-line">
    <div class="contents">
      <div class="user-info">
        <%= render partial: "info", locals: { user: @user, followings: @followings, followers: @followers } %>
      </div>
      <div class="content">
        <h4 class="title">フォロー中</h4>
        <% @followings.each do |following| %>
          <div class="follow-content">
            <div class="follow-upper-content">
              <div class="user-area">
                <div class="user-icon">
                  <%= link_to user_path(following) do %>
                    <% if following.icon.attached? %>
                      <%= image_tag following.icon, class: "icon" %>
                    <% else %>
                      <%= image_tag "default_user.png", class: "icon" %>
                    <% end %>
                </div>
                <div class="user">
                    <div class="user-name b">
                      <%= following.name %>
                    </div>
                    <div class="follow-account">
                      <%= following.account %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="follow-user-profile text">
              <%= following.profile %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="sub-contents">
      <%= render partial: "posts/recommendation", locals: { recommendation_users: @recommendation_users } %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="main-contents">
  <div class="time-line">
    <div class="contents">
      <div class="user-info">
        <%= render partial: "info", locals: { user: @user, followings: @followings, followers: @followers } %>
      </div>
      <% if current_user == @user %>
        <% @user_posts.each do |post| %>
          <%= render partial: "posts/post", locals: { post: post } %>
        <% end %>
      <% elsif @posts.blank? %>
        <h4 class="title">24時間以内の投稿はありません。</h4>
      <% else %>
        <% @posts.each do |post| %>
          <%= render partial: "posts/post", locals: { post: post } %>
        <% end %>
      <% end %>
    </div>
    <div class="sub-contents">
      <%= render partial: "posts/recommendation", locals: { recommendation_users: @recommendation_users } %>
    </div>
  </div>
</div>